# Generated by Django 5.1.6 on 2025-02-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='election',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='election',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.electioncampaign'),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
