# Generated by Django 5.1.6 on 2025-02-26 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election')},
        ),
    ]
