# Generated by Django 5.1.6 on 2025-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_election_end_time_remove_election_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionmanager',
            name='full_name',
        ),
        migrations.AddField(
            model_name='electionmanager',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electionmanager',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='electionmanager',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='electionmanager',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
