# Generated by Django 5.1.6 on 2025-02-25 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_electionmanager_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_profiles/')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.election')),
            ],
        ),
    ]
