# Generated by Django 5.1.6 on 2025-02-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
