# Generated by Django 5.1.6 on 2025-03-02 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_voter_is_approved_alter_voter_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='officer_profiles/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.electionmanager')),
            ],
        ),
    ]
