# Generated by Django 5.1.6 on 2025-03-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_electionofficer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionofficer',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='electionofficer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='electionofficer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='officers/'),
        ),
    ]
